TEMPLATE__REPORT_DATA = {
    "avgDefRate": {"total": None, "unitOfMeasure": None},
    "defTankLevel": {"total": None, "unitOfMeasure": None},
    "fuelTankLevel": {"total": None, "unitOfMeasure": "prcnt"},
    "avgFuelRate": {
        "working": None,
        "transport": None,
        "idle": None,
        "cfHigh": None,
        "cfMedium": None,
        "cfLow": None,
        "cfKeyOn": None,
        "cfIdle": None,
        "serviceGeneral": None,
        "serviceWrap": None,
        "serviceLube": None,
        "harvest": None,
        "forming": None,
        "wrapping": None,
        "ejecting": None,
        "idleWithCutterheadOff": None,
        "idleWithCutterheadOn": None,
        "feedrollReverse": None,
        "harvestingLowLoad": None,
        "harvestingMediumLoad": None,
        "harvestingHighLoad": None,
        "headlandTurnCutterheadOn": None,
        "transportBelowSixteenCutterheadOff": None,
        "transportAboveSixteenRoadSwitchOn": None,
        "harvesting": None,
        "maneuvering": None,
        "idleGrainTankNotFull": None,
        "idleGrainTankFull": None,
        "unloadingNotHarvesting": None,
        "harvestingUnloading": None,
        "headlandTurnSeparatorEngaged": None,
        "transportBelowSixteenSeparatorOff": None,
        "total": None,
        "unitOfMeasure": "l/hr",
    },
    "utilization": {
        "working": None,
        "transport": None,
        "idle": None,
        "cfHigh": None,
        "cfMedium": None,
        "cfLow": None,
        "cfKeyOn": None,
        "cfIdle": None,
        "serviceGeneral": None,
        "serviceWrap": None,
        "serviceLube": None,
        "harvest": None,
        "forming": None,
        "wrapping": None,
        "ejecting": None,
        "idleWithCutterheadOff": None,
        "idleWithCutterheadOn": None,
        "feedrollReverse": None,
        "harvestingLowLoad": None,
        "harvestingMediumLoad": None,
        "harvestingHighLoad": None,
        "headlandTurnCutterheadOn": None,
        "transportBelowSixteenCutterheadOff": None,
        "transportAboveSixteenRoadSwitchOn": None,
        "harvesting": None,
        "maneuvering": None,
        "idleGrainTankNotFull": None,
        "idleGrainTankFull": None,
        "unloadingNotHarvesting": None,
        "harvestingUnloading": None,
        "headlandTurnSeparatorEngaged": None,
        "transportBelowSixteenSeparatorOff": None,
        "total": None,
        "unitOfMeasure": "hours",
    },
    "defConsumption": {
        "working": None,
        "transport": None,
        "idle": None,
        "cfHigh": None,
        "cfMedium": None,
        "cfLow": None,
        "cfKeyOn": None,
        "cfIdle": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "fuelConsumption": {
        "working": None,
        "transport": None,
        "idle": None,
        "cfHigh": None,
        "cfMedium": None,
        "cfLow": None,
        "cfKeyOn": None,
        "cfIdle": None,
        "serviceGeneral": None,
        "serviceWrap": None,
        "serviceLube": None,
        "harvest": None,
        "forming": None,
        "wrapping": None,
        "ejecting": None,
        "idleWithCutterheadOff": None,
        "idleWithCutterheadOn": None,
        "feedrollReverse": None,
        "harvestingLowLoad": None,
        "harvestingMediumLoad": None,
        "harvestingHighLoad": None,
        "headlandTurnCutterheadOn": None,
        "transportBelowSixteenCutterheadOff": None,
        "transportAboveSixteenRoadSwitchOn": None,
        "harvesting": None,
        "maneuvering": None,
        "idleGrainTankNotFull": None,
        "idleGrainTankFull": None,
        "unloadingNotHarvesting": None,
        "harvestingUnloading": None,
        "headlandTurnSeparatorEngaged": None,
        "transportBelowSixteenSeparatorOff": None,
        "total": None,
        "unitOfMeasure": "l",
    },
    "autotrac": {
        "active": None,
        "inActive": None,
        "activePercentage": None,
        "total": None,
        "unitOfMeasure": "hours",
    },
    "rowsense": {
        "active": None,
        "inActive": None,
        "activePercentage": None,
        "total": None,
        "unitOfMeasure": "hours",
    },
    "harvestSmart": {
        "on": None,
        "off": None,
        "onPercentage": None,
        "total": None,
        "unitOfMeasure": "hours",
    },
    "autoHeaderFloat": {
        "on": None,
        "off": None,
        "onPercentage": None,
        "total": None,
        "unitOfMeasure": "hours",
    },
    "autoHeaderHeight": {
        "on": None,
        "off": None,
        "onPercentage": None,
        "total": None,
        "unitOfMeasure": "hours",
    },
    "autoHeaderHeightFlexHeader": {
        "on": None,
        "off": None,
        "onPercentage": None,
        "total": None,
        "unitOfMeasure": "hours",
    },
    "autoMaintain": {
        "on": None,
        "off": None,
        "onPercentage": None,
        "total": None,
        "unitOfMeasure": "hours",
    },
    "autoReelPosition": {
        "on": None,
        "off": None,
        "onPercentage": None,
        "total": None,
        "unitOfMeasure": "hours",
    },
    "autoReelSpeed": {
        "on": None,
        "off": None,
        "onPercentage": None,
        "total": None,
        "unitOfMeasure": "hours",
    },
    "efficiencyManagerOnTime": {
        "manual": None,
        "auto": None,
        "autoPercentage": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "smartGradeOperatingModeUtilization": {
        "gradingOnly": None,
        "cutting": None,
        "spreading": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "smartGradeUtilization": {
        "guidance": None,
        "control": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "engineLoadRate": {
        "working": None,
        "transport": None,
        "idle": None,
        "cfHigh": None,
        "cfMedium": None,
        "cfLow": None,
        "cfKeyOn": None,
        "cfIdle": None,
        "serviceGeneral": None,
        "serviceWrap": None,
        "serviceLube": None,
        "harvest": None,
        "forming": None,
        "wrapping": None,
        "ejecting": None,
        "idleWithCutterheadOff": None,
        "idleWithCutterheadOn": None,
        "feedrollReverse": None,
        "harvestingLowLoad": None,
        "harvestingMediumLoad": None,
        "harvestingHighLoad": None,
        "headlandTurnCutterheadOn": None,
        "transportBelowSixteenCutterheadOff": None,
        "transportAboveSixteenRoadSwitchOn": None,
        "harvesting": None,
        "maneuvering": None,
        "idleGrainTankNotFull": None,
        "idleGrainTankFull": None,
        "unloadingNotHarvesting": None,
        "harvestingUnloading": None,
        "headlandTurnSeparatorEngaged": None,
        "transportBelowSixteenSeparatorOff": None,
        "total": None,
        "unitOfMeasure": "prcnt",
    },
    "vision": {
        "active": None,
        "inActive": None,
        "activePercentage": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "sectionControlTime": {
        "active": None,
        "inActive": None,
        "activePercentage": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "avgEngineSpeed": {
        "working": None,
        "transport": None,
        "idle": None,
        "serviceGeneral": None,
        "serviceWrap": None,
        "serviceLube": None,
        "harvest": None,
        "forming": None,
        "wrapping": None,
        "ejecting": None,
        "idleWithCutterheadOff": None,
        "idleWithCutterheadOn": None,
        "feedrollReverse": None,
        "harvestingLowLoad": None,
        "harvestingMediumLoad": None,
        "harvestingHighLoad": None,
        "headlandTurnCutterheadOn": None,
        "transportBelowSixteenCutterheadOff": None,
        "transportAboveSixteenRoadSwitchOn": None,
        "harvesting": None,
        "maneuvering": None,
        "idleGrainTankNotFull": None,
        "idleGrainTankFull": None,
        "unloadingNotHarvesting": None,
        "harvestingUnloading": None,
        "headlandTurnSeparatorEngaged": None,
        "transportBelowSixteenSeparatorOff": None,
        "unitOfMeasure": "RPM",
    },
    "avgGroundSpeed": {
        "working": None,
        "transport": None,
        "idle": None,
        "serviceGeneral": None,
        "serviceWrap": None,
        "serviceLube": None,
        "harvest": None,
        "forming": None,
        "wrapping": None,
        "ejecting": None,
        "idleWithCutterheadOff": None,
        "idleWithCutterheadOn": None,
        "feedrollReverse": None,
        "harvestingLowLoad": None,
        "harvestingMediumLoad": None,
        "harvestingHighLoad": None,
        "headlandTurnCutterheadOn": None,
        "transportBelowSixteenCutterheadOff": None,
        "transportAboveSixteenRoadSwitchOn": None,
        "harvesting": None,
        "maneuvering": None,
        "idleGrainTankNotFull": None,
        "idleGrainTankFull": None,
        "unloadingNotHarvesting": None,
        "harvestingUnloading": None,
        "headlandTurnSeparatorEngaged": None,
        "transportBelowSixteenSeparatorOff": None,
        "average": None,
        "unitOfMeasure": "km/hr",
    },
    "avgCoolantTemp": {"total": None, "unitOfMeasure": "C"},
    "maxCoolantTemp": {"total": None, "unitOfMeasure": "C"},
    "avgHydraulicOilTemp": {"total": None, "unitOfMeasure": "C"},
    "maxHydraulicOilTemp": {"total": None, "unitOfMeasure": "C"},
    "avgTransOilTemp": {"total": None, "unitOfMeasure": None},
    "maxTransOilTemp": {"total": None, "unitOfMeasure": None},
    "lifetimeExhaustFilterCleanings": {
        "completed": None,
        "aborted": None,
        "ratio": None,
        "unitOfMeasure": None,
    },
    "separatorHours": {
        "period": None,
        "_8000": None,
        "total": None,
        "unitOfMeasure": "hours",
    },
    "totalSeparatorHours": {"total": None, "unitOfMeasure": "hours"},
    "wheelSlippage": {
        "v0_2": None,
        "v2_4": None,
        "v4_6": None,
        "v6_8": None,
        "v8_10": None,
        "v10_12": None,
        "v12_14": None,
        "v14_16": None,
        "v16_18": None,
        "v18_100": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "sixWheelDriveUtilization": {
        "sixWheelDriveOn": None,
        "sixWheelDriveOff": None,
        "sixWheelDriveOnPercentage": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "sixWheelDriveAggressiveness": {
        "sand": None,
        "grading": None,
        "ditching": None,
        "mud": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "difflock": {
        "on": None,
        "off": None,
        "onPercentage": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "mfwd": {
        "on": None,
        "off": None,
        "onPercentage": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "slipControlTime": {
        "active": None,
        "inactive": None,
        "activePercentage": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "rearPTO": {
        "on": None,
        "off": None,
        "onPercentage": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "fieldCruise": {
        "on": None,
        "off": None,
        "onPercentage": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "manualDriving": {
        "manualDrivingOff": None,
        "manualDrivingOn": None,
        "manualDrivingOnPercentage": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "ipm": {
        "on": None,
        "off": None,
        "onPercentage": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "ivtAutoMode": {
        "ivtAutoModeManual": None,
        "ivtAutoModeFullAutoCustom": None,
        "ivtAutoModeFullAutoCustomPercentage": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "distanceTraveled": {"total": None, "unitOfMeasure": None},
    "fanHours": {"total": None, "unitOfMeasure": None},
    "periodElevatorHours": {"total": None, "unitOfMeasure": None},
    "totalElevatorHours": {"total": None, "unitOfMeasure": None},
    "forwardReverseDistanceTraveled": {
        "forward": None,
        "reverse": None,
        "forwardPercentage": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "forwardReverseTravelTime": {
        "forward": None,
        "reverse": None,
        "forwardPercentage": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "sootLevel": {
        "veryLow": None,
        "low": None,
        "moderate": None,
        "high": None,
        "veryHigh": None,
        "serviceRequired": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "timeInGear": {
        "rev4": None,
        "rev3": None,
        "rev2": None,
        "rev1": None,
        "neutral": None,
        "fwd1": None,
        "fwd2": None,
        "fwd3": None,
        "fwd4": None,
        "fwd5": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "timeInGearConstruction": {
        "rev8": None,
        "rev7": None,
        "rev6": None,
        "rev5": None,
        "rev4": None,
        "rev3": None,
        "rev2": None,
        "rev1": None,
        "neutral": None,
        "fwd1": None,
        "fwd2": None,
        "fwd3": None,
        "fwd4": None,
        "fwd5": None,
        "fwd6": None,
        "fwd7": None,
        "fwd8": None,
        "park": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "timeInCorn": {
        "time": None,
        "_8000": None,
        "total": None,
        "unitOfMeasure": "hours",
    },
    "timeInBeansOrPeas": {
        "time": None,
        "_8000": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "timeInWheat": {"time": None, "_8000": None, "total": None, "unitOfMeasure": None},
    "timeInCanola": {"time": None, "_8000": None, "total": None, "unitOfMeasure": None},
    "timeInSoybeans": {
        "time": None,
        "_8000": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "engineModeUtilization": {
        "manualMode": None,
        "headLandMode": None,
        "economyMode": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "activeYield": {
        "on": None,
        "off": None,
        "onPercentage": None,
        "total": None,
        "unitOfMeasure": "hours",
    },
    "activeTerrainAdjustment": {
        "on": None,
        "off": None,
        "onPercentage": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "headerTypeUtilization": {
        "unknown": None,
        "choppingCorn": None,
        "rowCrop": None,
        "corn": None,
        "beltPickup": None,
        "rigidPlatform": None,
        "flexibleDraper": None,
        "otherDraper": None,
        "flex": None,
        "extendable": None,
        "total": None,
        "unitOfMeasure": "hours",
    },
    "baseCutterHeightAutoControl": {
        "on": None,
        "off": None,
        "onPercentage": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "cropDividerFloatAutoControl": {
        "on": None,
        "off": None,
        "onPercentage": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "autoFieldCruise": {
        "on": None,
        "off": None,
        "onPercentage": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "topperUtilization": {
        "left": None,
        "right": None,
        "off": None,
        "topperOnPercentage": None,
        "topperOn": None,
        "unitOfMeasure": None,
    },
    "cutterheadHours": {"total": None, "unitOfMeasure": None},
    "cutterhead": {"_0": None, "total": None, "unitOfMeasure": None},
    "avgLengthOfCut": {"total": None, "unitOfMeasure": None},
    "avgCutterheadSpeed": {"total": None, "unitOfMeasure": None},
    "avgFeedrollSpeed": {"total": None, "unitOfMeasure": None},
    "shearbarAdjustmentCount": {"total": None, "unitOfMeasure": None},
    "avgCutterheadHoursShearbarAdjustment": {
        "operatingHours": None,
        "shearbarCount": None,
        "averageHours": None,
        "unitOfMeasure": None,
    },
    "pulsing": {
        "active": None,
        "inActive": None,
        "activePercentage": None,
        "unitOfMeasure": None,
    },
    "applicationTime": {"time": None, "unitOfMeasure": None},
    "avgBoomPressure": {"total": None, "unitOfMeasure": None},
    "totalBucketCount": {"buckets": None, "unitOfMeasure": None},
    "totalPayload": {"tons": None, "unitOfMeasure": None},
    "totalTimeLoading": {"time": None, "unitOfMeasure": None},
    "totalTrucksLoaded": {"total": None, "unitOfMeasure": None},
    "avgTruckPayloadWeight": {"total": None, "unitOfMeasure": None},
    "truckLoadsPerHour": {
        "time": None,
        "totalTrucksLoaded": None,
        "truckLoadsPerHour": None,
        "unitOfMeasure": None,
    },
    "weightLoadedPerHour": {
        "tons": None,
        "time": None,
        "weightLoadedPerHour": None,
        "unitOfMeasure": None,
    },
    "autoshiftUtilization": {
        "on": None,
        "off": None,
        "onPercentage": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "lockUpTorqueConverterUtilization": {
        "on": None,
        "off": None,
        "onPercentage": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "ecoModeUtilization": {
        "disabled": None,
        "enabled": None,
        "off": None,
        "on": None,
        "enabledPercentage": None,
        "unitOfMeasure": None,
    },
    "excavatorAttachmentUtilization": {
        "bucket": None,
        "breaker": None,
        "pulverizer": None,
        "crusher": None,
        "vibratoryHammer": None,
        "thumbMode": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "excavatorFunctionUtilization": {
        "noActivity": None,
        "travelOnly": None,
        "swingOnly": None,
        "digOnly": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "excavatorEngineModeSetting": {
        "economyMode": None,
        "performanceMode": None,
        "highPowerMode": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "backhoeUtilization": {
        "backhoeIdle": None,
        "backhoe": None,
        "backhoeEconomy": None,
        "loaderIdle": None,
        "loader": None,
        "loaderEconomy": None,
        "backhoeTransport": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "gradeControlSystemUtilization": {
        "gradeControlSystemOff": None,
        "deereCrossSlopeEnabled": None,
        "integratedGradeControlEnabled": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "gradeControlUtilization": {
        "guidance": None,
        "control": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "crossSlopeUtilization": {
        "guidance": None,
        "automaticControl": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "engineFuelUtilizationRate": {
        "keyOn": None,
        "idle": None,
        "low": None,
        "medium": None,
        "high": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "integratedGradeControlUtilization": {
        "manual": None,
        "auto": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "frontLeftTirePressureMin": {"total": None, "unitOfMeasure": None},
    "frontRightTirePressureMin": {"total": None, "unitOfMeasure": None},
    "midRearLeftTirePressureMin": {"total": None, "unitOfMeasure": None},
    "midRearRightTirePressureMin": {"total": None, "unitOfMeasure": None},
    "rearLeftTirePressureMin": {"total": None, "unitOfMeasure": None},
    "rearRightTirePressureMin": {"total": None, "unitOfMeasure": None},
    "frontLeftTirePressureMax": {"total": None, "unitOfMeasure": None},
    "frontRightTirePressureMax": {"total": None, "unitOfMeasure": None},
    "midRearLeftTirePressureMax": {"total": None, "unitOfMeasure": None},
    "midRearRightTirePressureMax": {"total": None, "unitOfMeasure": None},
    "rearLeftTirePressureMax": {"total": None, "unitOfMeasure": None},
    "rearRightTirePressureMax": {"total": None, "unitOfMeasure": None},
    "frontLeftTireTemperatureMin": {"total": None, "unitOfMeasure": None},
    "frontRightTireTemperatureMin": {"total": None, "unitOfMeasure": None},
    "midRearLeftTireTemperatureMin": {"total": None, "unitOfMeasure": None},
    "midRearRightTireTemperatureMin": {"total": None, "unitOfMeasure": None},
    "rearLeftTireTemperatureMin": {"total": None, "unitOfMeasure": None},
    "rearRightTireTemperatureMin": {"total": None, "unitOfMeasure": None},
    "frontLeftTireTemperatureMax": {"total": None, "unitOfMeasure": None},
    "frontRightTireTemperatureMax": {"total": None, "unitOfMeasure": None},
    "midRearLeftTireTemperatureMax": {"total": None, "unitOfMeasure": None},
    "midRearRightTireTemperatureMax": {"total": None, "unitOfMeasure": None},
    "rearLeftTireTemperatureMax": {"total": None, "unitOfMeasure": None},
    "rearRightTireTemperatureMax": {"total": None, "unitOfMeasure": None},
    "smartCleanUsage": {
        "on": None,
        "off": None,
        "onPercentage": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "turnAutomation": {
        "on": None,
        "off": None,
        "onPercentage": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "seeAndSpray": {
        "active": None,
        "inActive": None,
        "activePercentage": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "seeAndSprayUltimate": {
        "active": None,
        "inActive": None,
        "activePercentage": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "leftCropDividerHeight": {"total": None, "unitOfMeasure": None},
    "rightCropDividerHeight": {"total": None, "unitOfMeasure": None},
    "primaryExtractorFanSpeed": {"total": None, "unitOfMeasure": None},
    "timeAtPrimaryExtractorSpeed": {
        "below650RPM": None,
        "between650RPM700RPM": None,
        "between700RPM750RPM": None,
        "between750RPM800RPM": None,
        "between800RPM850RPM": None,
        "between850RPM900RPM": None,
        "between900RPM950RPM": None,
        "above950RPM": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "avgBasecutterHeight": {"total": None, "unitOfMeasure": None},
    "maxChopperPressure": {"total": None, "unitOfMeasure": None},
    "maxBasecutterPressure": {"total": None, "unitOfMeasure": None},
    "timeAtBasecutterPressure": {
        "below600PSI": None,
        "between600PSI800PSI": None,
        "between800PSI1000PSI": None,
        "between1000PSI1200PSI": None,
        "between1200PSI1400PSI": None,
        "between1400PSI1600PSI": None,
        "between1600PSI1800PSI": None,
        "above1800PSI": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "timeAtChopperPressure": {
        "below600PSI": None,
        "between600PSI800PSI": None,
        "between800PSI1000PSI": None,
        "between1000PSI1200PSI": None,
        "between1200PSI1400PSI": None,
        "between1400PSI1600PSI": None,
        "between1600PSI1800PSI": None,
        "above1800PSI": None,
        "total": None,
        "unitOfMeasure": None,
    },
    "idleHours": {"total": None, "unitOfMeasure": None},
    "totalOperationTime": {"total": None, "unitOfMeasure": None},
    "elevatorDriveSpeed": {"total": None, "unitOfMeasure": None},
    "rideControlUtilization": {
        "off": None,
        "on": None,
        "automatic": None,
        "onPercentage": None,
        "unitOfMeasure": None,
    },
    "coastControlUtilization": {
        "off": None,
        "setting1": None,
        "setting2": None,
        "setting3": None,
        "on": None,
        "onPercentage": None,
        "setting1OnPercentage": None,
        "setting2OnPercentage": None,
        "setting3OnPercentage": None,
        "unitOfMeasure": None,
    },
    "performanceModeUtilization": {
        "normal": None,
        "productivity": None,
        "normalPercentage": None,
        "productivityPercentage": None,
        "unitOfMeasure": None,
    },
    "transmissionModeStateUtilization": {
        "auto1DActive": None,
        "auto2DActive": None,
        "auto1DActivePercentage": None,
        "auto2DActivePercentage": None,
        "unitOfMeasure": None,
    },
    "lifetimeOdometer": {"total": None, "unitOfMeasure": None},
    "rimpullControlUtilization": {
        "off": None,
        "setting1": None,
        "setting2": None,
        "setting3": None,
        "setting4": None,
        "on": None,
        "onPercentage": None,
        "unitOfMeasure": None,
    },
    "enginePowerPercentage": {"total": None, "unitOfMeasure": None},
    "fuelConsumptionRate": {"total": None, "unitOfMeasure": None},
    "totalFuelUsed": {"total": None, "unitOfMeasure": None},
}
